import 'dart:convert';

import 'package:mission_mangal/model/user_model.dart';
import 'package:http/http.dart' as http;



final String apiURL = 'https://jsonplaceholder.typicode.com/users';

Future<List<Autogenerated>> fetchJSONData() async {

  var jsonResponse = await http.get(apiURL);

  if (jsonResponse.statusCode == 200) {

    final jsonItems = json.decode(jsonResponse.body).cast<Map<String, dynamic>>();
    // print(jsonItems);

    List<Autogenerated> usersList = jsonItems.map<Autogenerated>((json) {
      return Autogenerated.fromJson(json);
    }).toList();

    return usersList;

  } else {
    throw Exception('Failed to load data from internet');
  }
}